name: CI

on:
  pull_request:
    branches:
      - "master"
      - ".*beta.*"

jobs:
  deploy:
    name: "Push to NPM"
    if: success()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build Package
        run: npm run build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish Package
        run: |
          pat=".*beta.*"
          if [[ $GITHUB_REF =~ $pat ]];
            then
              npm publish --tag beta
            else
              npm publish 
          fi
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  documentation:
    name: Deploy Docs
    needs: deploy
    if: success() && github.ref == 'refs/heads/master' && github.base_ref == ''
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install typescript globally
        run: npm install -g typescript

      - name: Install typedoc
        run: npm i -g typedoc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Docs
        run: typedoc index.ts

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: docs
