/* tslint:disable */
/* eslint-disable */
/**
 * pollination-server
 * Pollination Server OpenAPI Definition
 *
 * The version of the OpenAPI document: 1.7.0
 * Contact: info@pollination.solutions
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AppServerRestAccessPoliciesDtoPermission } from './app-server-rest-access-policies-dto-permission';
// May contain unused imports in some cases
// @ts-ignore
import type { Subject } from './subject';

/**
 * 
 * @export
 * @interface Accessor
 */
export interface Accessor {
    /**
     * 
     * @type {AppServerRestAccessPoliciesDtoPermission}
     * @memberof Accessor
     */
    'permission': AppServerRestAccessPoliciesDtoPermission;
    /**
     * 
     * @type {Subject}
     * @memberof Accessor
     */
    'subject': Subject;
}



