/* tslint:disable */
/* eslint-disable */
/**
 * Pollination Server
 * Pollination Server OpenAPI Defintion
 *
 * The version of the OpenAPI document: 0.10.10
 * Contact: info@pollination.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface APIToken
 */
export interface APIToken {
    /**
     * Key value pairs of auth claims the API token is entitled to
     * @type {{ [key: string]: string; }}
     * @memberof APIToken
     */
    claims?: { [key: string]: string; };
    /**
     * The user friendly name of the API token
     * @type {string}
     * @memberof APIToken
     */
    name: string;
}


