/* tslint:disable */
/* eslint-disable */
/**
 * pollination-server
 * Pollination Server OpenAPI Definition
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: info@pollination.solutions
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AppServerRestBillingDtoPayLink
 */
export interface AppServerRestBillingDtoPayLink {
    /**
     * 
     * @type {string}
     * @memberof AppServerRestBillingDtoPayLink
     */
    'url': string;
}

