/* tslint:disable */
/* eslint-disable */
/**
 * pollination-server
 * Pollination Server OpenAPI Definition
 *
 * The version of the OpenAPI document: 1.8.1
 * Contact: info@pollination.solutions
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * DTO for Paddle Billing Price
 * @export
 * @interface BillingPrice
 */
export interface BillingPrice {
    /**
     * 
     * @type {number}
     * @memberof BillingPrice
     */
    'billing_cycle_frequency'?: number;
    /**
     * 
     * @type {string}
     * @memberof BillingPrice
     */
    'billing_cycle_interval'?: string;
    /**
     * 
     * @type {string}
     * @memberof BillingPrice
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof BillingPrice
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof BillingPrice
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof BillingPrice
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof BillingPrice
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof BillingPrice
     */
    'unit_price_amount': string;
    /**
     * 
     * @type {string}
     * @memberof BillingPrice
     */
    'unit_price_currency': string;
    /**
     * 
     * @type {string}
     * @memberof BillingPrice
     */
    'updated_at'?: string;
}

