/* tslint:disable */
/* eslint-disable */
/**
 * pollination-server
 * Pollination Server OpenAPI Definition
 *
 * The version of the OpenAPI document: 1.8.9
 * Contact: info@pollination.solutions
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BillingPrice } from './billing-price';

/**
 * DTO for Paddle Billing Product with prices
 * @export
 * @interface BillingProduct
 */
export interface BillingProduct {
    /**
     * 
     * @type {string}
     * @memberof BillingProduct
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof BillingProduct
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof BillingProduct
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof BillingProduct
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof BillingProduct
     */
    'plan_slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof BillingProduct
     */
    'plan_type'?: string;
    /**
     * 
     * @type {Array<BillingPrice>}
     * @memberof BillingProduct
     */
    'prices'?: Array<BillingPrice>;
    /**
     * 
     * @type {string}
     * @memberof BillingProduct
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof BillingProduct
     */
    'updated_at'?: string;
}

