/* tslint:disable */
/* eslint-disable */
/**
 * pollination-server
 * Pollination Server OpenAPI Definition
 *
 * The version of the OpenAPI document: 1.8.2
 * Contact: info@pollination.solutions
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * DTO for Paddle Billing Transaction
 * @export
 * @interface BillingTransaction
 */
export interface BillingTransaction {
    /**
     * 
     * @type {string}
     * @memberof BillingTransaction
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof BillingTransaction
     */
    'currency_code': string;
    /**
     * 
     * @type {string}
     * @memberof BillingTransaction
     */
    'customer_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof BillingTransaction
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof BillingTransaction
     */
    'status': string;
    /**
     * 
     * @type {string}
     * @memberof BillingTransaction
     */
    'subscription_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof BillingTransaction
     */
    'total_amount': string;
    /**
     * 
     * @type {string}
     * @memberof BillingTransaction
     */
    'updated_at': string;
}

