/* tslint:disable */
/* eslint-disable */
/**
 * pollination-server
 * Pollination Server OpenAPI Definition
 *
 * The version of the OpenAPI document: 0.12.3
 * Contact: info@pollination.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BodyPostRecipeRegistriesOwnerRecipesPost
 */
export interface BodyPostRecipeRegistriesOwnerRecipesPost {
    /**
     * 
     * @type {any}
     * @memberof BodyPostRecipeRegistriesOwnerRecipesPost
     */
    _package: any;
}


