/* tslint:disable */
/* eslint-disable */
/**
 * Pollination Server
 * Pollination Server OpenAPI Defintion
 *
 * The version of the OpenAPI document: 0.9.2
 * Contact: info@pollination.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FileMeta
 */
export interface FileMeta {
    /**
     * 
     * @type {string}
     * @memberof FileMeta
     */
    fileName: string;
    /**
     * 
     * @type {string}
     * @memberof FileMeta
     */
    key: string;
    /**
     * 
     * @type {Date}
     * @memberof FileMeta
     */
    lastModified?: Date;
    /**
     * 
     * @type {number}
     * @memberof FileMeta
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof FileMeta
     */
    type: string;
}


