/* tslint:disable */
/* eslint-disable */
/**
 * pollination-server
 * Pollination Server OpenAPI Definition
 *
 * The version of the OpenAPI document: 0.28.0
 * Contact: info@pollination.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FileMeta
 */
export interface FileMeta {
    /**
     * 
     * @type {string}
     * @memberof FileMeta
     */
    file_name: string;
    /**
     * 
     * @type {string}
     * @memberof FileMeta
     */
    file_type: string;
    /**
     * 
     * @type {string}
     * @memberof FileMeta
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof FileMeta
     */
    last_modified?: string;
    /**
     * 
     * @type {number}
     * @memberof FileMeta
     */
    size?: number;
}


