/* tslint:disable */
/* eslint-disable */
/**
 * Pollination Server
 * Pollination Server OpenAPI Defintion
 *
 * The version of the OpenAPI document: v0.9.0
 * Contact: info@pollination.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * An Input Parameter Reference
 * @export
 * @interface InputParameterReference
 */
export interface InputParameterReference {
    /**
     * 
     * @type {string}
     * @memberof InputParameterReference
     */
    type?: InputParameterReferenceTypeEnum;
    /**
     * The name of the DAG input variable
     * @type {string}
     * @memberof InputParameterReference
     */
    variable: string;
}

/**
    * @export
    * @enum {string}
    */
export enum InputParameterReferenceTypeEnum {
    Inputs = 'inputs'
}



