/* tslint:disable */
/* eslint-disable */
/**
 * pollination-server
 * Pollination Server OpenAPI Definition
 *
 * The version of the OpenAPI document: 1.9.0
 * Contact: info@pollination.solutions
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LicensePoolPublic } from './license-pool-public';

/**
 * 
 * @export
 * @interface LicensePoolList
 */
export interface LicensePoolList {
    /**
     * 
     * @type {Array<LicensePoolPublic>}
     * @memberof LicensePoolList
     */
    'resources': Array<LicensePoolPublic>;
}

