/* tslint:disable */
/* eslint-disable */
/**
 * Pollination Server
 * Pollination Server OpenAPI Defintion
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: info@pollination.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OrgRoleEnum } from './org-role-enum';

/**
 * 
 * @export
 * @interface OrgMemberDto
 */
export interface OrgMemberDto {
    /**
     * 
     * @type {OrgRoleEnum}
     * @memberof OrgMemberDto
     */
    role: OrgRoleEnum;
    /**
     * The org member account id
     * @type {string}
     * @memberof OrgMemberDto
     */
    user_id: string;
}


