/* tslint:disable */
/* eslint-disable */
/**
 * pollination-server
 * Pollination Server OpenAPI Definition
 *
 * The version of the OpenAPI document: 1.7.0
 * Contact: info@pollination.solutions
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AccountPublic } from './account-public';
// May contain unused imports in some cases
// @ts-ignore
import type { AppDomainsOrganizationRolesEntitiesPermission } from './app-domains-organization-roles-entities-permission';

/**
 * 
 * @export
 * @interface OrganizationRole
 */
export interface OrganizationRole {
    /**
     * A description of the role
     * @type {string}
     * @memberof OrganizationRole
     */
    'description': string;
    /**
     * The display name for this role
     * @type {string}
     * @memberof OrganizationRole
     */
    'display_name': string;
    /**
     * The name of the role that is being bound to the user
     * @type {string}
     * @memberof OrganizationRole
     */
    'name': string;
    /**
     * The account that owns the role
     * @type {AccountPublic}
     * @memberof OrganizationRole
     */
    'owner': AccountPublic;
    /**
     * The resources that the role can access
     * @type {{ [key: string]: AppDomainsOrganizationRolesEntitiesPermission; }}
     * @memberof OrganizationRole
     */
    'resources'?: { [key: string]: AppDomainsOrganizationRolesEntitiesPermission; };
}

