/* tslint:disable */
/* eslint-disable */
/**
 * Pollination Server
 * Pollination Server OpenAPI Defintion
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: info@pollination.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { PackageAbridgedDto } from './package-abridged-dto';

/**
 * A list response from a pagination request
 * @export
 * @interface PackageListDto
 */
export interface PackageListDto {
    /**
     * The next page, if this on is not the last
     * @type {number}
     * @memberof PackageListDto
     */
    next_page?: number;
    /**
     * The current page the pagination request is on
     * @type {number}
     * @memberof PackageListDto
     */
    page: number;
    /**
     * The total number of pages
     * @type {number}
     * @memberof PackageListDto
     */
    page_count: number;
    /**
     * The number of pages per pagination request
     * @type {number}
     * @memberof PackageListDto
     */
    per_page: number;
    /**
     * 
     * @type {Array<PackageAbridgedDto>}
     * @memberof PackageListDto
     */
    resources: Array<PackageAbridgedDto>;
    /**
     * The total number of resources matching the list request
     * @type {number}
     * @memberof PackageListDto
     */
    total_count: number;
}


