/* tslint:disable */
/* eslint-disable */
/**
 * pollination-server
 * Pollination Server OpenAPI Definition
 *
 * The version of the OpenAPI document: 1.8.7
 * Contact: info@pollination.solutions
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PaddleBillingPrice } from './paddle-billing-price';
// May contain unused imports in some cases
// @ts-ignore
import type { PaddleBillingProduct } from './paddle-billing-product';

/**
 * 
 * @export
 * @interface PaddleBillingSubscriptionItem
 */
export interface PaddleBillingSubscriptionItem {
    /**
     * 
     * @type {string}
     * @memberof PaddleBillingSubscriptionItem
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaddleBillingSubscriptionItem
     */
    'next_billed_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof PaddleBillingSubscriptionItem
     */
    'previously_billed_at'?: string;
    /**
     * 
     * @type {PaddleBillingPrice}
     * @memberof PaddleBillingSubscriptionItem
     */
    'price': PaddleBillingPrice;
    /**
     * 
     * @type {PaddleBillingProduct}
     * @memberof PaddleBillingSubscriptionItem
     */
    'product': PaddleBillingProduct;
    /**
     * 
     * @type {number}
     * @memberof PaddleBillingSubscriptionItem
     */
    'quantity': number;
    /**
     * 
     * @type {boolean}
     * @memberof PaddleBillingSubscriptionItem
     */
    'recurring'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PaddleBillingSubscriptionItem
     */
    'status': string;
    /**
     * 
     * @type {object}
     * @memberof PaddleBillingSubscriptionItem
     */
    'trial_dates'?: object;
    /**
     * 
     * @type {string}
     * @memberof PaddleBillingSubscriptionItem
     */
    'updated_at'?: string;
}

