/* tslint:disable */
/* eslint-disable */
/**
 * Pollination Server
 * Pollination Server OpenAPI Defintion
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: info@pollination.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PatchOrgDto
 */
export interface PatchOrgDto {
    /**
     * The contact email for the organisation
     * @type {string}
     * @memberof PatchOrgDto
     */
    contact_email: string;
    /**
     * A description of the org
     * @type {string}
     * @memberof PatchOrgDto
     */
    description?: string;
    /**
     * The pretty name of the org
     * @type {string}
     * @memberof PatchOrgDto
     */
    name: string;
    /**
     * The avatar picture for the Org
     * @type {string}
     * @memberof PatchOrgDto
     */
    picture: string;
}


