/* tslint:disable */
/* eslint-disable */
/**
 * Pollination Server
 * Pollination Server OpenAPI Defintion
 *
 * The version of the OpenAPI document: v0.9.0
 * Contact: info@pollination.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { PolicySubject } from './policy-subject';

/**
 * 
 * @export
 * @interface ProjectAccessPolicy
 */
export interface ProjectAccessPolicy {
    /**
     * The permission given to the subject of the access policy
     * @type {string}
     * @memberof ProjectAccessPolicy
     */
    permission: ProjectAccessPolicyPermissionEnum;
    /**
     * The subject of the access policy
     * @type {PolicySubject}
     * @memberof ProjectAccessPolicy
     */
    subject: PolicySubject;
}

/**
    * @export
    * @enum {string}
    */
export enum ProjectAccessPolicyPermissionEnum {
    Admin = 'admin',
    Write = 'write',
    Read = 'read'
}



