/* tslint:disable */
/* eslint-disable */
/**
 * Pollination Server
 * Pollination Server OpenAPI Defintion
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: info@pollination.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProjectPolicySubjectDto
 */
export interface ProjectPolicySubjectDto {
    /**
     * The ID of the policy subject
     * @type {string}
     * @memberof ProjectPolicySubjectDto
     */
    id: string;
    /**
     * The role within the policy subject that the access policy refers
     * @type {string}
     * @memberof ProjectPolicySubjectDto
     */
    role: string;
    /**
     * The type of policy subject. Can be `team`, `org` or `user`
     * @type {string}
     * @memberof ProjectPolicySubjectDto
     */
    type: string;
}


