/* tslint:disable */
/* eslint-disable */
/**
 * Pollination Server
 * Pollination Server OpenAPI Defintion
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: info@pollination.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { License } from './license';
import { QueenbeeRecipeMetadataMaintainer } from './queenbee-recipe-metadata-maintainer';

/**
 * Recipe metadata information.
 * @export
 * @interface QueenbeeRecipeMetadataMetaData
 */
export interface QueenbeeRecipeMetadataMetaData {
    /**
     * Whether this recipe is deprecated
     * @type {boolean}
     * @memberof QueenbeeRecipeMetadataMetaData
     */
    deprecated?: boolean;
    /**
     * A description of what this recipe does
     * @type {string}
     * @memberof QueenbeeRecipeMetadataMetaData
     */
    description?: string;
    /**
     * The URL of this recipe\'s home page
     * @type {string}
     * @memberof QueenbeeRecipeMetadataMetaData
     */
    home?: string;
    /**
     * A URL to an SVG or PNG image to be used as an icon
     * @type {string}
     * @memberof QueenbeeRecipeMetadataMetaData
     */
    icon?: string;
    /**
     * A list of keywords to search the recipe by
     * @type {Array<string>}
     * @memberof QueenbeeRecipeMetadataMetaData
     */
    keywords?: Array<string>;
    /**
     * The license information.
     * @type {License}
     * @memberof QueenbeeRecipeMetadataMetaData
     */
    license?: License;
    /**
     * A list of maintainers for the recipe
     * @type {Array<QueenbeeRecipeMetadataMaintainer>}
     * @memberof QueenbeeRecipeMetadataMetaData
     */
    maintainers?: Array<QueenbeeRecipeMetadataMaintainer>;
    /**
     * Recipe name. Make it descriptive and helpful ;)
     * @type {string}
     * @memberof QueenbeeRecipeMetadataMetaData
     */
    name: string;
    /**
     * A list of URLs to source code for this project
     * @type {Array<string>}
     * @memberof QueenbeeRecipeMetadataMetaData
     */
    sources?: Array<string>;
    /**
     * The tag of the recipe
     * @type {string}
     * @memberof QueenbeeRecipeMetadataMetaData
     */
    tag: string;
}


