/* tslint:disable */
/* eslint-disable */
/**
 * Pollination Server
 * Pollination Server OpenAPI Defintion
 *
 * The version of the OpenAPI document: v0.9.0
 * Contact: info@pollination.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RepositoryCreate
 */
export interface RepositoryCreate {
    /**
     * description
     * @type {string}
     * @memberof RepositoryCreate
     */
    description?: string;
    /**
     * icon
     * @type {string}
     * @memberof RepositoryCreate
     */
    icon?: string;
    /**
     * keywords
     * @type {Array<string>}
     * @memberof RepositoryCreate
     */
    keywords?: Array<string>;
    /**
     * The name of the repository
     * @type {string}
     * @memberof RepositoryCreate
     */
    name: string;
    /**
     * Whether or not a repository is publicly viewable
     * @type {boolean}
     * @memberof RepositoryCreate
     */
    _public?: boolean;
}


