/* tslint:disable */
/* eslint-disable */
/**
 * pollination-server
 * Pollination Server OpenAPI Definition
 *
 * The version of the OpenAPI document: 1.8.11
 * Contact: info@pollination.solutions
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResourcesDuration
 */
export interface ResourcesDuration {
    /**
     * 
     * @type {number}
     * @memberof ResourcesDuration
     */
    'cpu'?: number;
    /**
     * 
     * @type {number}
     * @memberof ResourcesDuration
     */
    'memory'?: number;
}

