/* tslint:disable */
/* eslint-disable */
/**
 * Pollination Server
 * Pollination Server OpenAPI Definition
 *
 * The version of the OpenAPI document: 0.10.12
 * Contact: info@pollination.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AccountPublic } from './account-public';
import { Job } from './job';
import { JobStatus } from './job-status';

/**
 * 
 * @export
 * @interface Run
 */
export interface Run {
    /**
     * author
     * @type {AccountPublic}
     * @memberof Run
     */
    author?: AccountPublic;
    /**
     * The unique ID for this run
     * @type {string}
     * @memberof Run
     */
    id: string;
    /**
     * 
     * @type {Job}
     * @memberof Run
     */
    job: Job;
    /**
     * owner
     * @type {AccountPublic}
     * @memberof Run
     */
    owner?: AccountPublic;
    /**
     * The status of the job
     * @type {JobStatus}
     * @memberof Run
     */
    status?: JobStatus;
}


