/* tslint:disable */
/* eslint-disable */
/**
 * Pollination Server
 * Pollination Server OpenAPI Defintion
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: info@pollination.cloud
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TaskStatus } from './task-status';

/**
 * Workflow Status
 * @export
 * @interface SimulationStatus
 */
export interface SimulationStatus {
    /**
     * The ID of the first task in the workflow
     * @type {string}
     * @memberof SimulationStatus
     */
    entrypoint?: string;
    /**
     * The time at which the task was completed
     * @type {string}
     * @memberof SimulationStatus
     */
    finished_at?: string;
    /**
     * The ID of the individual workflow run.
     * @type {string}
     * @memberof SimulationStatus
     */
    id: string;
    /**
     * Any message produced by the task. Usually error/debugging hints.
     * @type {string}
     * @memberof SimulationStatus
     */
    message?: string;
    /**
     * ID of the account the simulation is running for.
     * @type {string}
     * @memberof SimulationStatus
     */
    owner_id: string;
    /**
     * The max number of parallel tasks running for this simulation
     * @type {number}
     * @memberof SimulationStatus
     */
    parallelism?: number;
    /**
     * ID of the project the simulation belongs to
     * @type {string}
     * @memberof SimulationStatus
     */
    project_id: string;
    /**
     * ID of the recipe repository used to create the workflow
     * @type {string}
     * @memberof SimulationStatus
     */
    recipe_id: string;
    /**
     * ID of the recipe owner
     * @type {string}
     * @memberof SimulationStatus
     */
    recipe_owner_id: string;
    /**
     * ID of the specific recipe package used to create the workflow
     * @type {string}
     * @memberof SimulationStatus
     */
    recipe_package_id: string;
    /**
     * The time at which the task was started
     * @type {string}
     * @memberof SimulationStatus
     */
    started_at: string;
    /**
     * The status of this task. Can be \"Running\", \"Succeeded\", \"Failed\" or \"Error\"
     * @type {string}
     * @memberof SimulationStatus
     */
    status: string;
    /**
     * 
     * @type {{ [key: string]: TaskStatus; }}
     * @memberof SimulationStatus
     */
    tasks?: { [key: string]: TaskStatus; };
}


