/* tslint:disable */
/* eslint-disable */
/**
 * pollination-server
 * Pollination Server OpenAPI Definition
 *
 * The version of the OpenAPI document: 1.8.9
 * Contact: info@pollination.solutions
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TransactionTotals
 */
export interface TransactionTotals {
    /**
     * 
     * @type {string}
     * @memberof TransactionTotals
     */
    'balance': string;
    /**
     * 
     * @type {string}
     * @memberof TransactionTotals
     */
    'credit': string;
    /**
     * 
     * @type {string}
     * @memberof TransactionTotals
     */
    'credit_to_balance': string;
    /**
     * 
     * @type {string}
     * @memberof TransactionTotals
     */
    'currency_code': string;
    /**
     * 
     * @type {string}
     * @memberof TransactionTotals
     */
    'discount': string;
    /**
     * 
     * @type {string}
     * @memberof TransactionTotals
     */
    'earnings'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionTotals
     */
    'fee'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionTotals
     */
    'grand_total': string;
    /**
     * 
     * @type {string}
     * @memberof TransactionTotals
     */
    'subtotal': string;
    /**
     * 
     * @type {string}
     * @memberof TransactionTotals
     */
    'tax': string;
    /**
     * 
     * @type {string}
     * @memberof TransactionTotals
     */
    'total': string;
}

